### ISSUE TITLE
Test der Zugriffsrechte 2

### ISSUE THREAD

**Issue by suchja** [LMStudent/hallo-octocat#2]
Ich verstehe noch nicht, ob es möglich ist den Autor eines Issues als Assignee zu setzen. Das werde ich hiermit ausprobieren. suchja ist bei diesem Projekt nicht Collaborator.

**Comment by LMStudent** [comment]
NEIN! Nur Personen aus dem Projekt (also der Projektinhaber, oder Collaborator) können das Assignee verwendet werden.
